package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.MSBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.VisualStudioStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.dotnetRestore
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.msBuild
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.visualStudio
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        dotnetRestore {
            projects = "TeamcityTest/TeamcityTest.sln"
        }
        visualStudio {
            path = "TeamcityTest/TeamcityTest.sln"
            version = VisualStudioStep.VisualStudioVersion.vs2017
            runPlatform = VisualStudioStep.Platform.x86
            msBuildVersion = VisualStudioStep.MSBuildVersion.V15_0
            msBuildToolsVersion = VisualStudioStep.MSBuildToolsVersion.V15_0
            targets = "Clean"
        }
        visualStudio {
            path = "TeamcityTest/TeamcityTest.sln"
            version = VisualStudioStep.VisualStudioVersion.vs2013
            runPlatform = VisualStudioStep.Platform.x86
            msBuildVersion = VisualStudioStep.MSBuildVersion.V12_0
            msBuildToolsVersion = VisualStudioStep.MSBuildToolsVersion.V12_0
            targets = "Build"
            configuration = "Debug"
        }
    }
    steps {
        insert(1) {
            msBuild {
                path = "TeamcityTest/TeamcityTest.sln"
                toolsVersion = MSBuildStep.MSBuildToolsVersion.V15_0
                platform = MSBuildStep.Platform.x64
                targets = "Clean"
                args = "Configuration=Debug"
                param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
            }
        }
        items.removeAt(2)
    }
}
